default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gamou_development
  username: <%= ENV.fetch("DB_USER") { 'gamou' } %>
  password: <%= ENV.fetch("DB_PASS") { 'gamou' } %>
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>

test:
  <<: *default
  database: gamou_test
  username: <%= ENV.fetch("DB_USER") { 'gamou' } %>
  password: <%= ENV.fetch("DB_PASS") { 'gamou' } %>
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
